version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: donation-app
    container_name: donation-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
      - ./storage:/var/www/storage:rw
      - ./public:/var/www/public
    environment:
      - APP_ENV=local
    networks:
      - donation-network

  nginx:
    image: nginx:alpine
    container_name: donation-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - donation-network 
      
  db:
    image: mysql:8.0
    container_name: donation-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - donation-network
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin
    container_name: donation-phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - donation-network
      
  mailpit:
    image: axllent/mailpit
    container_name: donation-mailpit
    ports:
      - "1025:1025" # SMTP Server
      - "8025:8025" # Web Interface
    restart: unless-stopped
    networks:
      - donation-network

  frontend:
    image: node:18
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: donation-vue
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - donation-network

networks:
  donation-network:
    driver: bridge

volumes:
  dbdata:
    driver: local